on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version
        if: runner.os == 'Linux'
      - run: reg QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths" /s
        if: runner.os == 'Windows'
      - run: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
        if: runner.os == 'macOS'
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run pretest
      - run: npm run webpack
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
